package com.entloom.meta.contract.diagnostic;

/**
 * Meta 诊断编码。
 */
public enum MetaDiagnosticCode {
    UNKNOWN,
    MISSING_ENTITY_CLASS,
    MISSING_ENTITY_ANNOTATION,
    INDEX_FIELD_NOT_FOUND,
    RELATION_TARGET_ENTITY_NOT_FOUND,
    RELATION_SOURCE_FIELD_NOT_FOUND,
    RELATION_TARGET_FIELD_NOT_FOUND,
    FIELD_KIND_META_MISMATCH,
    INVALID_FIELD_CONSTRAINT,
    INVALID_DEFAULT_VALUE,
    DUPLICATE_INDEX,
    EXPLICIT_VALUE_CONFLICT,
    INFERRED_VALUE_USED,
    DEFAULT_VALUE_USED
}
