package com.entloom.meta.contract.diagnostic;

/**
 * Meta 诊断编码。
 */
public enum MetaDiagnosticCode {
    UNKNOWN,
    MISSING_ENTITY_CLASS,
    MISSING_ENTITY_ANNOTATION,
    INDEX_FIELD_NOT_FOUND,
    RELATION_TARGET_ENTITY_NOT_FOUND,
    RELATION_SOURCE_FIELD_NOT_FOUND,
    RELATION_TARGET_FIELD_NOT_FOUND,
    FIELD_KIND_META_MISMATCH,
    INVALID_FIELD_CONSTRAINT,
    INVALID_DEFAULT_VALUE,
    DUPLICATE_INDEX,
    EXPLICIT_VALUE_CONFLICT,
    INFERRED_VALUE_USED,
    DEFAULT_VALUE_USED,
    /** Contribution 缺少合法目标或属性。 */
    CONTRIBUTION_STRUCTURAL_CONFLICT,
    /** Contribution 同级规则产生不同值。 */
    CONTRIBUTION_SAME_PRIORITY_CONFLICT,
    /** 同一属性的 Contribution 值类型不一致。 */
    CONTRIBUTION_TYPE_MISMATCH,
    /** 消费者识别到当前声明，但尚未实现该属性语义。 */
    CONSUMER_UNSUPPORTED_PROPERTY
}
