spring:
  config:
    import: optional:file:./.env[.properties]
  application:
    name: customer-profile-spring-boot
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

server:
  port: ${APP_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
