ent:
  loom:
    meta:
      entity-class-names:
        - com.example.minicommerce.product.entity.Product
        - com.example.minicommerce.customer.entity.Customer
        - com.example.minicommerce.order.entity.Order
        - com.example.minicommerce.order.entity.OrderItem
      crud:
        enabled: true
      doc:
        enabled: true

entloom:
  doc:
    contract:
      enabled: true
      http:
        enabled: true
  crud:
    controller:
      enabled: true
      base-path: /api/ent-crud
      include-entities:
        - product
        - customer
    query:
      enabled: true
    command:
      enabled: true
    import:
      enabled: false
    export:
      enabled: false
    sql-log:
      mode: safe
    governance:
      permission-rules:
        - resource: order
          action: COMMAND:ACTION
          scene: place
          decision: ALLOW
          subject-ids:
            - local-developer
        - resource: order
          action: QUERY:DETAIL
          scene: detail
          decision: ALLOW
          subject-ids:
            - local-developer
        - resource: product
          action: '*'
          scene: '*'
          decision: ALLOW
          subject-ids:
            - local-developer
        - resource: customer
          action: '*'
          scene: '*'
          decision: ALLOW
          subject-ids:
            - local-developer
      audit:
        persist-to-jdbc: false
